redis:
    image: tutum/redis
    environment:
      - "REDIS_PASS=**None**"
api:
    build: .
    volumes:
        - .:/code
    links:
        - redis
    ports:
        - "8002:80"
    environment:
        - REDIS_URL=redis://redis:6379/1
        - API_KEY=foobar
        - DEBUG=true
    env_file: .env
